<?php
// $Revision$

/**
 * Implementation of hook_menu().
 */
function imis_auth_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path'               => 'admin/settings/imis_auth',
      'title'              => 'iMIS Member authentication',
      'callback'           => 'drupal_get_form',
      'callback arguments' => array('imis_auth_settings'),
      'access'             => user_access('administer site configuration'),
      'description'        => t('Let users login to the site and access content using their web login and password.'),
    );
  }

  return $items;
}

/**
 * Settings for the module
 *
 * @ingroup form
 */
function imis_auth_settings() {
  $form['settings'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Settings'),
    '#description'   => t('iMIS member site host name to authenticate against. You have to include the <em>http://</em> prefix.'),
  );

  $form['settings']['imis_auth_host'] =  array(
    '#type'          => 'textfield',
    '#title'         => t('Host'),
    '#default_value' => variable_get('imis_auth_host', ''),
    '#description'   => t('The host name to authenticate against.'),
  );

  $form['settings']['imis_auth_message'] = array(
    '#type'          => 'textarea',
    '#title'         => t('Login notice'),
    '#default_value' => variable_get('imis_auth_message', ''),
    '#description'   => t('You can include a note that will apear below the login form and the login block to notify users that they can authenticate using iMIS credentials.'),
  );

  $form['settings']['imis_auth_exempt'] = array(
    '#type'          => 'textarea',
    '#title'         => t('Exempt users'),
    '#default_value' => variable_get('imis_auth_exempt', ''),
    '#description'   => t('List of Drupal User IDs on this site to exempt from iMIS authentication. Enter one uid per line. These users will login using their Drupal credentials, and can have roles in addition to "authenticated user".'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_form_alter().
 *
 * Change the normal form login form behavior.
 *
 * @ingroup form
 */
function imis_auth_form_alter($form_id, &$form) {
  switch ($form_id) {
    case 'user_login':
      // Login form extra info
      $msg = variable_get('imis_auth_message', '');
      if ($msg) {
        $form['member-auth'] = array(
          '#value'  => $msg,
          '#prefix' => '<div>',
          '#suffix' => '</div>',
        );
      }

      // Reset the validate and submit functions
      $form['#validate'] = array('imis_auth_login_validate' => array());
      break;

    case 'user_login_block':
      // Reset the validate and submit functions
      $form['#validate'] = array('imis_auth_login_validate' => array());
      break;

  }
}

/**
 * List of users to exempt
 */
function imis_auth_exempt_list() {
  $list = array();

  // Get the list of exempt users
  $list = explode("\n", variable_get('imis_auth_exempt', ''));
  if (!in_array(1, $list)) {
    // Check if uid 1 is in the array
    $list[] = 1;
  }

  // remove new lines and other stuff from the values
  $sanitized_list = array();

  foreach($list as $key => $value) {
    $sanitized_list[$key] = trim($value);
  }
  // Return list
  return $sanitized_list;
}

/**
 * Validate the user based on another Drupal site
 *
 * @ingroup $form
 */
function imis_auth_login_validate(&$form, &$form_state) {
  // Get the name and password fields from the form
  $name = $form_state['name'];
  // The password as entered by the user
  $pass = $form_state['pass'];

  // Check if the account already exists or its a new user
  $account = user_load(array('name' => $name));
  if (isset($account->uid)) {
    // Find out if the user is in the list of exempt users
    foreach(imis_auth_exempt_list() as $key => $uid) {
      if ($uid == $account->uid) {
        // This is the site admin, don't use external authentication, but normal authentication
        user_authenticate($name, $pass);
        return;
      }
    }
  }

  // Check if the user is in the member database
  $ret = imis_auth_webservice($name, $pass);
  if (!$ret['result']) {
    // User does not have a valid name/pass in the imis_members table
    form_set_error('name', $ret['message']);
  }
  else {
    // Remote login is valid
    $uid = db_result(db_query("SELECT uid FROM {imis_members} WHERE member_id = %d", $ret['id']));
    if ($uid != 0 && $uid == $account->uid) {
      // User already exists in Drupal, so we make them logged in
      global $user;
      $user = $account;
      return;
    }
    else {
      // User is in the table, save a Drupal user out of it.
      // We do not call user_external_login_register() because it assumes the "regular" way of Drupal
      // user registration, i.e. generate a random password, ...etc. We don't want that workflow.
      imis_auth_user_save($name, $pass, $ret['id']);
    }
  }
}

/**
 * Save the user data to the Drupal user's table
 */
function imis_auth_user_save($name, $pass, $member_id) {
  global $user;

  // Create a user array from the data
  $module = 'imis_auth';
  $userinfo = array(
    'name'             => $name,
    'pass'             => md5($pass),
    'init'             => $name,
    'status'           => 1,
    'access'           => time(),
    "authname_$module" => $name,
  );
  // Save it to the user table
  $account = user_save('', $userinfo);

  // Save the info from 
  db_query("DELETE FROM {imis_members} WHERE member_id = %d", $member_id);
  db_query("INSERT INTO {imis_members} (member_id, uid) VALUES (%d, %d)", $member_id, $account->uid);

  // Set the global variable
  $user = $account;

  // Log this information
  watchdog('user', t('New member: %name via %module.', array('%name' => $name, '%module' => $module)), WATCHDOG_NOTICE, l(t('edit'), 'user/'. $user->uid .'/edit'));
}

/**
 * Web service processing
 */
function imis_auth_webservice($name = '', $pass = '') {
  $host = variable_get('imis_auth_host', '');
  if (!$host) {
    // Host is not defined, return a message.
    $msg = t('This site is not configured correctly for remote member authentication. Please contact the administrator.');
    watchdog('imis_auth', $msg, WATCHDOG_ERROR);
    return array(
      'result'  => FALSE,
      'message' => $msg,
    );
  }

  // The URL to send the web service authentication requests to
  $url = $host . '/loginwebservice.asmx/ValidateLogin';

  // An array of POST variables
  $data = array(
    'Username' => $name,
    'Password' => $pass,
  );
  // Header for mime type
  $headers = array(
    'Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8',
  );

  // Post to the host
  $result = drupal_http_request($url, $headers, 'POST', http_build_query($data, '', '&'));

  if ($result->code != 200) {
    // Request not successful
    $msg = t('Attempt to authenticate user %name at host %host failed with HTTP error code: %code.',
      array('%name' => $name, '%host' => $host, '%code' => $result->code));

    // Log the error to the watchdog
    watchdog('imis_auth', $msg, WATCHDOG_ERROR);

    // Return a message
    return array(
      'result'  => FALSE,
      'message' => $msg,
      );
  }

  // Parse the XML
  $login_results  = imis_auth_parse_xml($result->data, '<LoginResults>');

  // Get the values
  $code = imis_auth_parse_xml($login_results, '<ResultCode>');
  $msg  = imis_auth_parse_xml($login_results, '<ResultMessage>');
  $id   = imis_auth_parse_xml($login_results, '<ID>');

  if (!is_numeric($id)) {
    // No numeric ID returned, so return an error
    return array(
      'result'  => FALSE,
      'message' => $msg,
      );
  }

  return array(
    // We are successful, return the ID and the message
    'result'  => TRUE,
    'id'      => $id,
    'message' => $msg,
    );
}

/**
 * A simple xml parsing function.
 * 
 * @param  $xml        A text string that contains the xml to be parsed.
 * @param  $open_tag   The opening xml tag to search for.
 * @return string      The string between $open_tag and its close tag.
 */
function imis_auth_parse_xml($xml, $open_tag) {
  $close_tag = '</'. substr($open_tag, 1, strlen($open_tag));
  $pos1 = strpos($xml, $open_tag);
  $pos2 = strpos($xml, $close_tag);
  return trim(substr($xml, $pos1 + strlen($open_tag), $pos2 - ($pos1 + strlen($open_tag))));
}

/**
 * Implementation of hook_user()
 */
function imis_auth_user($op, &$edit, &$account, $category = NULL) {
  switch($op) {
    case 'delete':
      db_query("DELETE FROM {imis_members} WHERE uid = %d", $account->uid);
      break;
  }
}
